services:
  app:
    image: 'mproxyapp:lastest'
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    ports:
      - '8080:8080'
  redis:
    image: 'redis:latest'
    ports:
      - '6379:6379'
#  postgres:
#    image: 'postgres:latest'
#    environment:
#      - 'POSTGRES_DB=oneproxydatabase'
#      - 'POSTGRES_PASSWORD=secret_one_proxy'
#      - 'POSTGRES_USER=oneproxy'
#    ports:
#      - '5432'
